[package]
name = "importenv"
version = "0.0.6"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/VHSgunzo/importenv"
description = "Launching an executable file with environment variables from a specific process id"

[profile.release]
strip = "symbols"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
chrono = "*"
nix = "*"
