name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: importenv
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Build
        run: cargo build --release

      - name: Build archlinux package
        uses: countstarlight/arch-makepkg-action@master
        with:
          packages: pacman-contrib
          scripts: "cp target/x86_64-unknown-linux-musl/release/importenv . && updpkgsum && makepkg"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: importenv importenv-*.pkg*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
